In [37]:
import numpy as np
print(np.zeros(10))
#muestra 10 ceros
print(np.ones(10))
#Muestra 10 unos
print(np.ones(10)*5)
#igual con 5

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [38]:
print(np.arange(10,51))
#Números del 10 al 50
print(np.arange(10,51,2))
#Números pares del 10 al 50

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [39]:
print(np.arange(0,9).reshape(3,3))
#matriz de 3x3 del 0 al 8
print(np.eye(3))
#Matriz de identidad 3x3
print(np.random.rand(25))
#25 números aleatorios
print(np.linspace(0,10,20))
#20 valores del 0 al 10

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.14895384 0.12722959 0.51674144 0.66444991 0.52550445 0.88685147
 0.08428942 0.98302264 0.32916044 0.15872488 0.3991885  0.69063469
 0.79892312 0.06349586 0.10028667 0.04320406 0.16320088 0.30272575
 0.04800871 0.55303934 0.1524886  0.17423019 0.7392528  0.41371644
 0.7463792 ]
[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [68]:
mat = np.arange(1,51).reshape(5,10)
print(mat)
#Ahora ver la matriz
print(mat[2])
#Ver la 3 fila
print(mat[:,1])
#Ver la 2 columna
print(mat[2:,1:])
#Muestra el array a partir de la 3 fila y 2 columna
print(mat[3,4])
#Muestra fila 5 en la columna 4
print(mat[:3,1:2])
#tres primeras filas de la 2 columna devuelve submatriz
print(mat.sum())
#Suma de los valores
print(mat.std())
#Desviación estandard
print(mat.sum(axis=0))
#Suma por columnas

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
[21 22 23 24 25 26 27 28 29 30]
[ 2 12 22 32 42]
[[22 23 24 25 26 27 28 29 30]
 [32 33 34 35 36 37 38 39 40]
 [42 43 44 45 46 47 48 49 50]]
35
[[ 2]
 [12]
 [22]]
1275
14.430869689661812
[105 110 115 120 125 130 135 140 145 150]
